// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("huaweicloudreceiver")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/huaweicloudreceiver"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
	LogsStability    = component.StabilityLevelDevelopment
)
